version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ithaka-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Opción 1: SQLite (desarrollo)
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
      # Opción 2: PostgreSQL (producción) - descomenta la siguiente línea y comenta SQLite
      # - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/ithaka
    volumes:
      # Mount source code for development (optional - remove for production)
      - ./app:/app/app:ro
      # Para persistir datos SQLite
      - ./data:/app/data
    # depends_on:  # Descomenta si usas PostgreSQL
    #   - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database (descomenta todo este bloque para usar PostgreSQL)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: ithaka-postgres
  #   environment:
  #     POSTGRES_DB: ithaka
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

# volumes:
#   postgres_data:
