apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ithaka-backend-route
  namespace: ithaka-backend
  labels:
    app: ithaka-backend
spec:
  http:
  - name: ithaka-backend-http
    match:
      hosts:
      - ithaka-backend.reto-ucu.net
      paths:
      - /*
    backends:
    - serviceName: ithaka-backend-service
      servicePort: 80
    plugins:
    - name: cors
      enable: true
      config:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "*"
        max_age: 86400
