apiVersion: v1
kind: ConfigMap
metadata:
  name: ithaka-backend-config
  namespace: ithaka-backend
  labels:
    app: ithaka-backend
data:
  DATABASE_URL: "sqlite+aiosqlite:///./app.db"
  PYTHONPATH: "/app"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
