apiVersion: v1
kind: Service
metadata:
  name: ithaka-backend-service
  namespace: ithaka-backend
  labels:
    app: ithaka-backend
spec:
  selector:
    app: ithaka-backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
